<a href="https://colab.research.google.com/github/audrb1999/DL-Project/blob/main/numpy_XOR_%EA%B5%AC%ED%98%84/01.%EA%B8%B0%EB%B3%B8%EC%A0%81%EC%9D%B8%20%ED%81%B4%EB%9E%98%EC%8A%A4%20%EA%B5%AC%ED%98%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##***1.기본적인 클래스 구현***
1. Layer
2. Step function
3. Perceptron

In [1]:
class Layer:
    def __init__(self):# 모든 함수들이 공통으로 입출력을 조절
        self.input = None
        self.output = None
    
    def forward(self, x):# 모든 함수들이 공통으로 사용하는 순전파 
        self.input = x
        self.output = self._forward(x)
        return self.output

    def _forward(self, x):
        raise NotImplementedError


    

In [2]:
import numpy as np

class StepFunction(Layer):
    def _forward(self, x):
        y = x > 0
        return y.astype(np.int)

class Perceptron(Layer):
    def __init__(self, weights, bias, activation=None):
        super().__init__() # 만약 상위 클래스 Layer가 호출되지 않아도 실행할 수 있게하는 것
        self.weights = weights
        self.bias = bias
        self.activation = activation

    def _forward(self, x): # 활성화 함수 유무를 위한 if 문
        a = np.matmul(x, self.weights) + self.bias
        if self.activation != None:
            y = self.activation.forward(a)
            return y
        return a


1. 퍼셉트론이 제대로 동작하는지 확인

In [3]:
p = Perceptron(np.array([[1, 2], [3, 4]]), np.array([[5, 6]]))
p.forward(np.array([[0, 0], [1, 0], [0, 1]]))
# 작동!

array([[ 5,  6],
       [ 6,  8],
       [ 8, 10]])

2. 계단 함수가 제대로 동작하는지 확인

In [4]:
s = StepFunction()
s.forward(np.array([1, -4, 3, 0]))

array([1, 0, 1, 0])

3. 퍼셉트론과 계단함수를 이용


In [5]:
p = Perceptron(np.array([[1, -1], [-2, 0]]), np.array([[-3, 1]]), activation=s)
p.forward(np.array([[1, 2], [-3, -4]]))

array([[0, 0],
       [1, 1]])